### PR TITLE
create "underline <ins>" extension (#54)

### PR DESCRIPTION
**Pull request by pabranch**
copied from "strikethrough &lt;del&gt;" and renamed

Comments and suggestions are welcome.

### CODE REVIEW

**Comment by robinst** [comment]
Hey there, welcome! This looks good already, I only have one comment:

I think we should call the artifact, package and class names `ins` instead. Whether it's rendered as underline or something else depends on the CSS that's used in the end, and is out of control of this library. A user of the library might not even render to HTML but just parse text with it. Note that the [MDN entry about ins](https://developer.mozilla.org/en/docs/Web/HTML/Element/ins) says nothing about `ins` being underline. We can keep the mentioning of underline in the descriptions. (I know this contradicts a bit with what the `gfm-strikethrough` extension does, but there it's because we follow exactly what GitHub does and calls it.)

We also require that you sign this CLA (only one time because it's your first contribution): https://na2.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=3f94fbdc-2fbe-46ac-b14c-5d152700ae5d

Once you've done the above change and sign the CLA, I'll gladly merge this :).

**Comment by pabranch** [comment]
I am happy to make the name change. When I have a chance, I'll look over the CLA and send a new pull request. Thanks for such a prompt response!

**Comment by pabranch** [comment]
How does this copy sound for the README.md?

> ### Ins
>
>Enables underline of text by enclosing it in `++`. For example, in
>`hey ++you++`, `you` will be rendered as underline text. Uses the &lt;ins&gt; tag.
>
>Use class `InsExtension` in artifact `commonmark-ext-ins`.

**Comment by robinst** [comment]
Sounds good! Don't forget to change the package name as well :).

**Comment by pabranch** [comment]
CLA has been signed. Let me know if you need me to email you a copy.

**Comment by robinst** [comment]
Perfect, thank you! Will be included in the next release.

**Pull request merged**
